type Mutation {
  createUser(email: String!, password: String!): User!
  loginUser(email: String!, password: String!): String!
  logoutUser: Boolean!
}

type Query {
  request: String!
  node(id: ID!): Node!
  readUser(email: String!): User!
  readCurrentUser: User!
}

interface Node {
  id: ID!
}

type User implements Node {
  id: ID!
  email: String!
}

schema {
  query: Query
  mutation: Mutation
}
