
type User
{
    id: ID!
    email: String!
}

type Query 
{ 
    get(key: String!): String
}

type Mutation
{
    set(key: String!, value: String!): String!
    createUser(email: String!, password: String!): User
}
